VHDL_SOURCES = /home/lucas/cernbox/RandomStuff/FPGA_Simulation/VHDL_Sim/counter.vhd
TOPLEVEL=counter
MODULE=counter_tb
include $(shell cocotb-config --makefiles)/Makefile.inc
include $(shell cocotb-config --makefiles)/Makefile.sim

